### ISSUE TITLE
Скомпилированная статья устарела

### ISSUE THREAD

**Issue by iamakulov** [FrontenderMagazine/optimization-killers#8]
Привет!

[Скомпилированная версия статьи](http://frontender.info/optimization-killers/), похоже, не соответствует исходнику в Markdown. Например, в исходнике исправлена опечатка с двойным `case`-ом (#1), а в версии на сайте — нет.

**Comment by subzey** [comment]
Призываю @SilentImp или @iamstarkov. Тут, похоже, надо запустить магию вручную.

**Comment by iamstarkov** [comment]
сброс кеша не работает, я бессилен. @SilentImp помоги

**Comment by iamakulov** [comment]
Бамп? @SilentImp, выручай.

**Comment by SilentImp** [comment]
@iamakulov @iamstarkov должно было обновится. Проверьте.

**Comment by iamakulov** [comment]
Кажется, да. Спасибо!
